services:
  factorio:
    image: hideroot/dockerio:latest
    network_mode: host
    volumes:
      - ./config:/factorio/config
    env_file:
      - .env
    environment:
      - RESET_SCHEDULE=TUE:21:00,FRI:10:00,SUN:21:00
      - RESET_GAME_HOURS=30
    restart: unless-stopped
