services:
  factorio:
    image: hideroot/dockerio:latest
    network_mode: host
    volumes:
      - ./config:/factorio/config
    env_file:
      - .env
    environment:
      - RESET_SCHEDULE=WED:06:00,FRI:19:00,MON:06:00
      - RESET_GAME_HOURS=30
    restart: unless-stopped
