services:
  factorio:
    image: hideroot/dockerio:latest
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - ./config:/factorio/config
    env_file:
      - .env
    environment:
      - FACTORIO_SERVER_NAME=Factorio Speedrun Server
      - RESET_SCHEDULE=WED:06:00,FRI:19:00,MON:06:00
      - RESET_GAME_HOURS=30
      - SERVER_MODE=achievement
    restart: unless-stopped
