data:extend{
    {
        type = "int-setting",
        name = "dockerio-timelapse-width",
        setting_type = "runtime-global",
        default_value = 1920,
        minimum_value = 640,
        maximum_value = 3840,
        order = "a",
    },
    {
        type = "int-setting",
        name = "dockerio-timelapse-height",
        setting_type = "runtime-global",
        default_value = 1080,
        minimum_value = 360,
        maximum_value = 2160,
        order = "b",
    },
    {
        type = "int-setting",
        name = "dockerio-timelapse-framerate",
        setting_type = "runtime-global",
        default_value = 25,
        minimum_value = 1,
        maximum_value = 60,
        order = "c",
    },
    {
        type = "int-setting",
        name = "dockerio-timelapse-speed-gain",
        setting_type = "runtime-global",
        default_value = 60,
        minimum_value = 1,
        maximum_value = 600,
        order = "d",
    },
    {
        type = "bool-setting",
        name = "dockerio-timelapse-always-day",
        setting_type = "runtime-global",
        default_value = true,
        order = "e",
    },
    {
        type = "int-setting",
        name = "dockerio-timelapse-boundary",
        setting_type = "runtime-global",
        default_value = 5,
        minimum_value = 1,
        maximum_value = 20,
        order = "f",
    },
    {
        type = "double-setting",
        name = "dockerio-timelapse-transition-period",
        setting_type = "runtime-global",
        default_value = 1.5,
        minimum_value = 0,
        maximum_value = 10,
        order = "g",
    },
    {
        type = "string-setting",
        name = "dockerio-timelapse-format",
        setting_type = "runtime-global",
        default_value = "png",
        allowed_values = { "png", "jpg" },
        order = "h",
    },
}
